matrix:
  fast_finish: true
  include:
  - os: linux
    sudo: false
    language: python
    python: '3.6'
    if: type != cron
    env: DEPLOY="true"
  - os: linux
    sudo: false
    env: CONAN_LOGGING_LEVEL=10
    language: python
    python: '3.6'
    if: type = cron

install:
- ".travis/install.sh"

script:
- travis_wait 60 ".travis/run.sh"

after_success:
- codecov

deploy:
  - provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}
    on:
      tags: true
      condition: "$DEPLOY = 'true'"
  - provider: pypi
    user: ${TEST_PYPI_USERNAME}
    server: https://test.pypi.org/legacy/
    password: ${TEST_PYPI_PASSWORD}
    on:
      branch: master
      condition: "$DEPLOY = 'true'"
