sudo: false
language: python
dist: trusty

matrix:
  include:
  - os: linux
    language: python
    python: '3.7'
    if: type != cron
    env: TOXENV=py37-conan-dev
  - os: linux
    language: python
    python: '3.7'
    if: type != cron
    env:
      - DEPLOY="true"
      - TOXENV=py37-conan-latest

  - os: osx
    language: generic
    osx_image: xcode9
    if: type != cron
    env: TOXENV=py37-conan-dev
  - os: osx
    language: generic
    osx_image: xcode9
    if: type != cron
    env: TOXENV=py37-conan-latest

  - os: linux
    env: CONAN_LOGGING_LEVEL=10
    language: python
    python: '3.7'
    env: TOXENV=py37-conan-dev
    if: type = cron
  - os: linux
    env: CONAN_LOGGING_LEVEL=10
    language: python
    python: '3.7'
    env: TOXENV=py37-conan-latest
    if: type = cron

install:
- ".travis/install.sh"

script:
- travis_wait 60 ".travis/run.sh"

after_success:
- codecov

deploy:
  - provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}
    on:
      tags: true
      condition: "$DEPLOY = 'true'"
  - provider: pypi
    user: ${TEST_PYPI_USERNAME}
    server: https://test.pypi.org/legacy/
    password: ${TEST_PYPI_PASSWORD}
    on:
      branch: master
      condition: "$DEPLOY = 'true'"
