build: false


environment:
    PYTHON: "C:\Python37"
    PYTHON_VERSION: "3.7.0"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install -e .[test]

test_script:
- cd tests
- pytest -v --cov=bincrafters_remove_outdated
